### ISSUE TITLE
run vundle PluginUpdate result in vim-cljfmt errors

### ISSUE THREAD

**Issue by huahaiy** [venantius/vim-cljfmt#13]
Done!
Error detected while processing /Users/huahaiy/.vim/bundle/vim-cljfmt/plugin/cljfmt.vim:
line   16:
E122: Function <SNR>63_RequireCljfmt already exists, add ! to replace it
line   30:
E122: Function <SNR>63_GetCurrentBufferContents already exists, add ! to replace it
line   34:
E122: Function <SNR>63_GetReformatString already exists, add ! to replace it
line   44:
E122: Function <SNR>63_FilterOutput already exists, add ! to replace it
line   57:
E122: Function <SNR>63_GetFormattedFile already exists, add ! to replace it
Press ENTER or type command to continue

**Comment by venantius** [comment]
The latest commit should resolve this. (https://github.com/venantius/vim-cljfmt/commit/2fd0e16cf4202bad9cbf27404277f7f342c4b4fe)
