### ISSUE TITLE
"Missing :endif" error detected while processing function cljfmt#AutoFomrat

### ISSUE THREAD

**Issue by skilbjo** [venantius/vim-cljfmt#29]
![image](https://cloud.githubusercontent.com/assets/1145927/18926829/2e8a7b68-856e-11e6-9240-6a219ba9fefb.png)

What's going on?

**Comment by venantius** [comment]
My guess is that you've re-started your REPL, and this is the same issues as #28, which should have just been resolved in #31. Closing.
