### ISSUE TITLE
"No matching autocommands" filter only works for english locale

### ISSUE THREAD

**Issue by thccorni** [venantius/vim-cljfmt#30]
Hi,

when formatting my code I get 2 lines added to my clojure file, stating that no matching autocommands where found. I could figure out, that there is a statement in your code prohibiting the message "No matching autocommands" from being added to the output. Since I am using a german system I get the message in german ("Keine passenden Autokommandos"), so it is not recognized by this string comparison.
Maybe there is a possibility to check if no autocommand was found other than string comparison?

If I am doing something wrong, i apologize, i'm just starting to use vim...

**Comment by venantius** [comment]
Hm! I hadn't really considered the possibility. Feel free to open a PR for the German error string :)
