### ISSUE TITLE
Whole file highlight

### ISSUE THREAD

**Issue by elzibubble** [venantius/vim-cljfmt#36]
Hi, after I save my Clojure file, the whole file becomes highlighted as if I'd searched for '.'. I can clear it by setting @/. The problem goes away if I delete vim-cljfmt. I'm using 0.5.1 and cljfmt 0.5.7.

**Comment by venantius** [comment]
Does this happen on all projects, or a particular one?

**Comment by elzibubble** [comment]
It's stopped doing it! Damned if I know what changed. My code wasn't quite right when I was having the problem, but I tried breaking a form and it didn't start doing it again, even after I restarted the REPL.

Sorry to waste your time, I'll reopen if it reoccurs.

**Comment by venantius** [comment]
Haha, no worries. Terrible things, computers.

**Comment by elzibubble** [comment]
It's still doing it :|

I don't know what makes it happen though. REPL being open for a while? Anything I can test for you?

**Comment by venantius** [comment]
Does it happen under particular projects? If so, can I see the `project.clj`? Any error or stacktrace? What's in your `~/.lein/profiles.clj`? JVM version, Lein version, OS version.

**Comment by elzibubble** [comment]
It happens on the (very new) project I'm working on right now:

(defproject gresham/ccm-lib-biz "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [ymilky/franzy "0.0.1"]
                 [ymilky/franzy-nippy "0.0.1"]])

My profiles.clj:

{:user  {:plugins  [[cider/cider-nrepl "0.16.0"]
                    [lein-cljfmt "0.5.7"]
                    [lein-localrepo "0.5.4"]
                    ]
         :dependencies  [[cljfmt "0.5.1"]]
         }}

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

Leiningen 2.8.1 on Java 1.8.0_152 Java HotSpot(TM) 64-Bit Server VM

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"

Vim plugins in use, rather a lot sorry!

conque_2.3
ctrlp-py-matcher
ctrlp.vim
gundo.vim
jedi-vim
neocomplete
nerdtree
paredit.vim
pathogen.vim
rainbow_parentheses.vim
splitjoin.vim
SudoEdit.vim
supertab
syntastic
tabular
tags
vim-abolish
vim-accordion
vimagit
vim-argumentative
vim-better-whitespace
vim-classpath
vim-cljfmt
vim-clojure-static
vim-commentary
vim-dispatch
vim-dokumentary
vim-fireplace
vim-fugitive
vim-indent-object
vim-json
vim-leiningen
vim-misc
vim-projectionist
vim-repeat
vim-salve
vim-session
vim-speeddating
vim-surround
vim-textobj-indent
vim-textobj-parameter
vim-textobj-python
vim-textobj-user
vim-typedclojure
vim-unimpaired
vim-unstack
vim-yaml
xeno-vim

**Comment by venantius** [comment]
Hmm. Okay, yeah. My guess would be that there's a conflict with one of the vim plugins. Although you should have the cljfmt version set to the same as the lein-cljfmt version - I don't think that'd be an issue for vim-cljfmt but it's worth having an eye on.

What Vim version are you using? vim-clojure-static has shipped with Vim for some time so I doubt you need it. 

I'd try disabling other vim plugins selectively. I'd also recommend trying to come up with a minimum-reproducible code sample - something small the always triggers the behavior in question.

**Comment by hamann** [comment]
Happens for me, too. Sometimes at start, sometimes after several hours

```Plug 'joshdick/onedark.vim'
Plug 'kchmck/vim-coffee-script'
Plug 'vim-ruby/vim-ruby'
Plug 'elixir-lang/vim-elixir'
Plug 'elzr/vim-json'
Plug 'tpope/vim-endwise'
Plug 'cakebaker/scss-syntax.vim'
Plug 'ntpeters/vim-better-whitespace'
Plug 'lambdatoast/elm.vim'
Plug 'scrooloose/nerdtree'
Plug 'kopischke/vim-fetch'
Plug 'xolox/vim-misc'
Plug 'hashivim/vim-hashicorp-tools'
Plug 'mileszs/ack.vim'
Plug 'jimeh/tmux-themepack'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-fireplace'
Plug 'tpope/vim-surround'
Plug 'kovisoft/paredit'
Plug 'luochen1990/rainbow'
Plug 'ludovicchabant/vim-gutentags'
Plug 'ervandew/supertab'
Plug 'bhurlow/vim-parinfer'
Plug 'yggdroot/indentline'
Plug 'alvan/vim-closetag'
Plug 'dgrnbrg/vim-redl'
Plug 'slime-lang/vim-slime-syntax'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'majutsushi/tagbar'
Plug 'ryanoasis/vim-devicons'
Plug 'whatyouhide/vim-lengthmatters'
Plug 'venantius/vim-cljfmt'
Plug 'w0rp/ale'
```

**Comment by venantius** [comment]
One place to start might be checking for plugins with on-write hooks that vim-cljfmt could be conflicting with. I'm honestly not sure - I've never run into this behavior. 

The plugins I use that are Clojure-related are:
```
paredit.vim
vim-cljfmt
vim-clojure-static
vim-fireplace
vim-salve (which I only installed recently)
vim-surround
```

**Comment by venantius** [comment]
Closing this for lack of movement.
