### ISSUE TITLE
Possibly broken since last few commits?

### ISSUE THREAD

**Issue by danielbraun** [venantius/vim-cljfmt#40]
The Mar 27, 2018 commits (https://github.com/venantius/vim-cljfmt/commit/bb939c4d052815d84db4e8ca4f50e25a83526015, https://github.com/venantius/vim-cljfmt/commit/bb05a9c1bf77749effd359abbf03626c79881bbd, https://github.com/venantius/vim-cljfmt/commit/f4bbc04967202a2b94a0ebbb3485991489b9dcd4) have broken the plugin for me - it always says there's a syntax error in the Clojure file.
The error happens here: https://github.com/venantius/vim-cljfmt/blob/f4bbc04967202a2b94a0ebbb3485991489b9dcd4/plugin/cljfmt.vim#L95

When I checkout the previous commit, https://github.com/venantius/vim-cljfmt/commit/c20d61ca147ef2dda7c8b82670bcae0473e90120, the plugin works fine.

I'm not familiar enough with Vimscript to debug this, so I though I'd just report it here in case someone happens to run into the same issue.

**Comment by frankitox** [comment]
Same here @danielbraun. The difference is that I couldn't manage to use other commit to make it work. I still get the same error. The exception says something like `Unexpected EOF while reading start of :...`. It seems like it only throws the exception if there's a colon `:` in the file. :weary:

**Comment by venantius** [comment]
Would you mind providing a replicable example?

**Comment by frankitox** [comment]
Hi @venantius ! Finally It's working, phew! Sadly, I'm not exactly sure what turn out to be the issue in the first place. I managed to make it fail a couple times, but suddenly it started working without any problem.

**Comment by venantius** [comment]
As there hasn't been any further update on this I'm going to close it for the moment. We can always revisit once we have more clarity.

**Comment by saidone75** [comment]
Hi @venantius, I am getting the very same issue as @danielbraun due to something inside `s:replaceBuffer`.
