### ISSUE TITLE
How to load it when I set plugin in profiles file without declarating the project dependencies

### ISSUE THREAD

**Issue by mut0u** [venantius/vim-cljfmt#5]
I want to make emacs plugin using cljfmt to format clojure code. 

I want I can run `reformat-string` function use nrepl, not calling the `lein cljfmt fix` command, because it is too slow to start lein command. 

And I want and the plugin in `~/.lein/profiles.clj` file and I can run the command in all my projects without adding the dependencies in every lein project.

I have no idea whether it can work or not.

**Comment by venantius** [comment]
The general outline of what you're talking about is sound. It's very similar to how I've designed my plugins. I don't know a lot about how emacs works so I can't help you much there. Is there a particular part of this that you're looking for clarity about?
