### ISSUE TITLE
DO NOT USE THIS PLUGIN

### ISSUE THREAD

**Issue by stelcodes** [venantius/vim-cljfmt#50]
This plugin will erase your entire buffer and if you have autosave and didn't commit changes, you are fucked. Undo doesn't work too. Thanks a lot!!

**Comment by stelcodes** [comment]
Hey, sorry for leaving for this rude issue. I regret it. I'm embarrassed. I do appreciate this work put into this plugin. It's obviously just not working for me right now. I was very upset. I will try to be less rude online!

**Comment by venantius** [comment]
Hey - thanks for the apology. I'm really sorry that the plugin wiped out your hard work - I totally get how frustrating that must have been! 

I transitioned away from active coding a few years ago (sadly :() and so don't have a chance to really maintain this very much, but the behaviour you're describing is definitely high on the list of things I wish I could fix about it.
