### ISSUE TITLE
Peristent error after formatting & saving an invalid code

### ISSUE THREAD

**Issue by ravicious** [venantius/vim-cljfmt#6]
So basically if I add an extra paren and run `:Cljfmt`, the whole buffer contents get deleted. From then if I try to save the file I get the following error. After fixing the error and saving the file, I get the same error over and over again; I have to restart vim for it to disappear.

```
Error detected while processing function <SNR>47_BufWritePostHook..<SNR>47_UpdateErrors..<SNR>47_CacheErrors..37..36..SyntaxCheckers_clojure_eastwood_GetLocList:
line    5:
E121: Undefined variable: l:cljfmt_output
Error detected while processing function <SNR>47_BufWritePostHook..<SNR>47_UpdateErrors..<SNR>47_CacheErrors:
line   34:
E170: Missing :endfor
Error detected while processing function <SNR>47_BufWritePostHook..<SNR>47_UpdateErrors:
line   13:
E171: Missing :endif
```

I use both vim-eastwood and vim-cljfmt on mvim. My `~/.lein/profiles.clj` looks like this:

``` clojure
{:user {:plugins [[cider/cider-nrepl "0.8.2"]
                  [lein-cljfmt "0.1.7"]
                  [jonase/eastwood "0.2.1"]
                  ]
        :dependencies [
                       [lein-cljfmt "0.1.7"]
                       [jonase/eastwood "0.2.1"]
                       ]}}
```

**Comment by venantius** [comment]
I believe this should be fixed as of https://github.com/venantius/vim-cljfmt/commit/50e47e00b5442879b87cf1e202737c4a8294ea79. Please update and let me know if you're still experiencing the issue.

**Comment by ravicious** [comment]
The error is gone, but now autoformatting on save just stops working silently. `:Cljfmt` still works, though.

The first time I ran `:Cljfmt` after a failed autoformat, it took a little longer for vim-cljfmt to format the file, so I guess it had to reconnect to repl or something.

Also, after formatting invalid code with `:Cljfmt`, the content of the buffer gets deleted.

**Comment by ravicious** [comment]
Wow, I'm so dumb. I totally forgot that yesterday I turned off autoformatting in my vimrc, everything's fine now.

Anyway, formatting invalid code still yields an empty buffer, but I guess I should create a separate issue for that? You've fixed this one after all. ;)

**Comment by venantius** [comment]
Haha, awesome. Well, the latter's still definitely a bug that I'd like to iron out, so I'm going to leave this open until I've fixed that as well.

**Comment by venantius** [comment]
@ravicious I think this should be fixed with the latest commit (https://github.com/venantius/vim-cljfmt/commit/35760727bb221e218e821eb5cf73f923d84eb51f). At the very least, I've tested it with the extra-parens situation you've described and it works. Let me know if this actually works :P

**Comment by venantius** [comment]
Since there haven't been any updates on this front, I'm closing this issue.
